server:
  port: 9007

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: stock
          uri: lb://stock
          predicates:
            - Path=/stock/**
        - id: company
          uri: lb://company
          predicates:
            - Path=/company/**
        - id: stockdetails
          uri: lb://stockdetails
          predicates:
            - Path=/stockdetails/**

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka